#!/bin/sh

set -e

case "$1" in
    configure)
        # Update the dynamic linker cache after installing ld.so.conf.d configuration
        if [ -x "$(command -v ldconfig)" ]; then
            ldconfig
        fi
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

exit 0
