#!/bin/sh

set -e

case "$1" in
    remove|purge)
        # Update the dynamic linker cache after removing ld.so.conf.d configuration
        if [ -x "$(command -v ldconfig)" ]; then
            ldconfig
        fi
    ;;

    upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
    ;;

    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

exit 0
